# Generated by Django 4.2.7 on 2024-02-28 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0002_district_state_state_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TestApp.country')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TestApp.district')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TestApp.state')),
            ],
        ),
    ]
